### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 202-203: invalid continuation byte

### ISSUE THREAD

**Issue by quinnjones** [thesamesam/recover-broken-vdb#6]
I'm reaching a uncaught error when I run recover-broken-vdb on one of my machines.  I've run it on half a dozen other machines without incident.  I'm not sure how to overcome it.

The (partial) output of `recover-broken-vdb --verbose`:

```
# recover-broken-vdb --verbose
>>> Scanning system. This may take a few minutes.
>>> Package sys-fs/udev-init-scripts-34 is fine: not installing any dyn. linked executables or shared libs
>>> Skipping sys-fs/e2fsprogs-1.46.4 because PROVIDES and NEEDED exists
...
Skipping sys-kernel/linux-firmware-20211027's /lib/firmware/nvidia/tu104/gr/fecs_inst.bin because file says not a shared library or dyn. linked executable
Skipping sys-kernel/linux-firmware-20211027's /lib/firmware/nvidia/tu104/gr/fecs_data.bin because file says not a shared library or dyn. linked executable
Traceback (most recent call last):
  File "/usr/bin/recover-broken-vdb", line 33, in <module>
    sys.exit(load_entry_point('recover-broken-vdb==0.0.9', 'console_scripts', 'recover-broken-vdb')())
  File "/usr/lib/python3.9/site-packages/recover_broken_vdb/__init__.py", line 495, in start
    corrupt_pkgs, unexpected_case_found = find_corrupt_pkgs(
  File "/usr/lib/python3.9/site-packages/recover_broken_vdb/__init__.py", line 212, in find_corrupt_pkgs
    file_exec_result = file_exec.stdout.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 202-203: invalid continuation byte
```

It's not clear that the issue exists in sys-kernel/linux-firmware, but I've reinstalled it as a precaution.  I have also ensured that the system is up to date.

Here's my info, if that helps:

```
# emerge --info
Portage 3.0.28 (python 3.9.8-final-0, default/linux/amd64/17.1, gcc-11.2.0, glibc-2.33-r7, 5.10.27-gentoo x86_64)
=================================================================
System uname: Linux-5.10.27-gentoo-x86_64-Intel-R-_Core-TM-_i5-6500T_CPU_@_2.50GHz-with-glibc2.33
KiB Mem:     3096820 total,    394556 free
KiB Swap:    1048572 total,    407900 free
Timestamp of repository gentoo: Fri, 19 Nov 2021 08:30:01 +0000
Head commit of repository gentoo: 546e058d165aa113b77cf12401f747a7505181b2
sh bash 5.1_p8
ld GNU ld (Gentoo 2.37_p1 p0) 2.37
app-shells/bash:          5.1_p8::gentoo
dev-java/java-config:     2.3.1::gentoo
dev-lang/perl:            5.34.0-r3::gentoo
dev-lang/python:          3.9.8::gentoo
dev-util/cmake:           3.20.5::gentoo
sys-apps/baselayout:      2.7-r3::gentoo
sys-apps/openrc:          0.44.8::gentoo
sys-apps/sandbox:         2.25::gentoo
sys-devel/autoconf:       2.71-r1::gentoo
sys-devel/automake:       1.16.4::gentoo
sys-devel/binutils:       2.37_p1::gentoo
sys-devel/gcc:            11.2.0::gentoo
sys-devel/gcc-config:     2.4::gentoo
sys-devel/libtool:        2.4.6-r6::gentoo
sys-devel/make:           4.3::gentoo
sys-kernel/linux-headers: 5.10::gentoo (virtual/os-headers)
sys-libs/glibc:           2.33-r7::gentoo
Repositories:

gentoo
    location: /var/db/repos/gentoo
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000
    sync-rsync-verify-metamanifest: yes
    sync-rsync-verify-max-age: 24
    sync-rsync-extra-opts: 
    sync-rsync-verify-jobs: 1

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="@FREE"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-Os -mtune=generic -pipe -fomit-frame-pointer"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-Os -mtune=generic -pipe -fomit-frame-pointer"
DISTDIR="/net/files/storage/distfiles"
ENV_UNSET="CARGO_HOME DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN GOPATH PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-Os -mtune=generic -pipe -fomit-frame-pointer"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs buildpkg config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-li
bs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-Os -mtune=generic -pipe -fomit-frame-pointer"
GENTOO_MIRRORS="http://distfiles.gentoo.org"
LANG="en_US"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
LINGUAS="en en_US"
MAKEOPTS="-j1"
PKGDIR="/net/files/storage/packages/vbox-multilib"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.gi
t"
PORTAGE_TMPDIR="/var/tmp"
USE="acl acpi amd64 apache2 bzip2 cli crypt dri fortran gdbm iconv ipv6 libglvnd libtirpc multilib ncurses nls nptl offensive openmp pam pcre readline seccomp split-usr ssl unicode xattr zlib" ABI_X86="64" ADA_TARGET="gnat_2019" APACHE2_M
ODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav da
v_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FE
ATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx mmxext sse sse2" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock greis isync
 itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="libinput" KERNEL="linux" L10N="en en-US" LCD_DEVICES="bayrad cfontz cfontz633 glk 
hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LUA_SINGLE_TARGET="lua5-1" LUA_TARGETS="lua5-1" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php7-3 php7-4" POSTGRES_TARGETS="po
stgres12 postgres13" PYTHON_SINGLE_TARGET="python3_9" PYTHON_TARGETS="python3_9" RUBY_TARGETS="ruby26 ruby27" USERLAND="GNU" VIDEO_CARDS="amdgpu fbdev intel nouveau radeon radeonsi vesa dummy v4l" XTABLES_ADDONS="quota2 psd pknock lscan l
ength2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq proto steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, RUSTFLAGS
```

**Comment by thesamesam** [comment]
Thanks for the report! ```file /lib/firmware/nvidia/tu104/*/*``` seems to give sensible output for me, at least.

We should just skip if we hit a decode error, but I'm curious as to how/why it's happening. I'll add some debugging output.

**Comment by quinnjones** [comment]
Thank you for looking at this.  (Really, I should start by thanking you for writing the script to fix the vdb in the first place.)

I've figured out that the specific error seems to be particular to this one system, and I can't figure out why it's different.  It's not your problem, though.

I think your idea of skipping on decode error seems sensible, in case this comes up again for someone else.  I've found the specific files that are triggering the error by adding output to the script.  Temporarily removing them allows the process to finish.

Here's my findings, for posterity.  If I accidentally stumble on a fix for whatever is causing this difference, I won't be able to replicate it later.

Results on the "bad" system:

```
# file -b /lib/firmware/nvidia/tu102/sec2/sig.bin
MacBinary, ID 0x2, comment length 10, total length 33554432, 2nd header length 1024, Mon Feb 13 15:30:56 2040 INVALID date, modified Mon Feb  6 19:40:32 2040, creator '    ', type '    ', 458752 bytes "�=\010\011\232�\234#�\226\027" 
# md5sum /lib/firmware/nvidia/tu102/sec2/sig.bin
6634c6b34dbcc552847026fdc8db5cf7  /lib/firmware/nvidia/tu102/sec2/sig.bin
```

Results from a known-good system:

```
$ file -b /lib/firmware/nvidia/tu102/sec2/sig.bin
MacBinary, ID 0x2, comment length 10, total length 33554432, 2nd header length 1024, Mon Feb 13 15:30:56 2040 INVALID date, modified Mon Feb  6 19:40:32 2040, creator '    ', type '    ', 458752 bytes "\342\262=\010\011\232\321\234#\312\226\027" 
$ md5sum /lib/firmware/nvidia/tu102/sec2/sig.bin
6634c6b34dbcc552847026fdc8db5cf7  /lib/firmware/nvidia/tu102/sec2/sig.bin
```

As you can see, the checksums are identical but the results from `file` are different.  Both systems have identical locale settings, not sure what else would trigger the poor unicode decode.

I'll try a few things, starting with rebuilding glibc, but this is not your problem.  Thanks again for looking into it!
